/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.swing.view;

import java.awt.Dimension;
import javax.swing.ImageIcon;
import javax.swing.JFrame;

/**
 *
 * @author rafaelgentil
 */
public class LoginView extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public LoginView() {
        initComponents();
       
        setTitle("Tela de Login");
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        loginPanel = new javax.swing.JPanel();
        loginLabel = new javax.swing.JLabel();
        senhaLabel = new javax.swing.JLabel();
        senhaField = new javax.swing.JPasswordField();
        loginField = new javax.swing.JTextField();
        informativoLabel = new javax.swing.JLabel();
        logarButton = new javax.swing.JButton();
        cancelarButton = new javax.swing.JButton();
        primeiroAcesButton = new javax.swing.JButton();
        fundoTelaLabel = new javax.swing.JLabel();
        primeiroAcessoPanel = new javax.swing.JPanel();
        cpfLabel = new javax.swing.JLabel();
        cpfField = new javax.swing.JTextField();
        informativoLabel1 = new javax.swing.JLabel();
        logarPrimAcesButton = new javax.swing.JButton();
        cancelarPrimAcesButton = new javax.swing.JButton();
        logotipoLabel1 = new javax.swing.JLabel();
        fundoTelaPrimAcesLabel = new javax.swing.JLabel();

        setResizable(false);
        setSize(new java.awt.Dimension(589, 192));

        jPanel1.setLayout(null);

        loginPanel.setBackground(java.awt.SystemColor.activeCaptionBorder);
        loginPanel.setLayout(null);

        loginLabel.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        loginLabel.setText("Login");
        loginPanel.add(loginLabel);
        loginLabel.setBounds(300, 40, 50, 20);

        senhaLabel.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        senhaLabel.setText("Senha");
        loginPanel.add(senhaLabel);
        senhaLabel.setBounds(300, 80, 50, 20);

        senhaField.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        senhaField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                senhaFieldActionPerformed(evt);
            }
        });
        loginPanel.add(senhaField);
        senhaField.setBounds(350, 80, 221, 24);

        loginField.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        loginPanel.add(loginField);
        loginField.setBounds(350, 40, 221, 24);

        informativoLabel.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        informativoLabel.setForeground(new java.awt.Color(255, 0, 0));
        loginPanel.add(informativoLabel);
        informativoLabel.setBounds(350, 10, 220, 30);

        logarButton.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        logarButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/delfos/res/logar30x30.png"))); // NOI18N
        logarButton.setText("Login");
        logarButton.setToolTipText("Logar");
        logarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logarButtonActionPerformed(evt);
            }
        });
        loginPanel.add(logarButton);
        logarButton.setBounds(480, 120, 80, 40);

        cancelarButton.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        cancelarButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/delfos/res/cancelar45x45.png"))); // NOI18N
        cancelarButton.setText("Cancelar");
        cancelarButton.setToolTipText("Cancelar");
        loginPanel.add(cancelarButton);
        cancelarButton.setBounds(370, 120, 100, 40);

        primeiroAcesButton.setText("Primeiro acesso");
        loginPanel.add(primeiroAcesButton);
        primeiroAcesButton.setBounds(140, 120, 130, 23);
        loginPanel.add(fundoTelaLabel);
        fundoTelaLabel.setBounds(3, 0, 590, 190);

        jPanel1.add(loginPanel);
        loginPanel.setBounds(-1, -2, 590, 190);

        primeiroAcessoPanel.setLayout(null);

        cpfLabel.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        cpfLabel.setText("CPF");
        primeiroAcessoPanel.add(cpfLabel);
        cpfLabel.setBounds(210, 40, 50, 30);

        cpfField.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        primeiroAcessoPanel.add(cpfField);
        cpfField.setBounds(260, 40, 221, 24);

        informativoLabel1.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        informativoLabel1.setForeground(new java.awt.Color(255, 0, 0));
        primeiroAcessoPanel.add(informativoLabel1);
        informativoLabel1.setBounds(350, 10, 220, 30);

        logarPrimAcesButton.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        logarPrimAcesButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/delfos/res/ok45x45.png"))); // NOI18N
        logarPrimAcesButton.setToolTipText("Solicitar Acesso");
        logarPrimAcesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logarPrimAcesButtonActionPerformed(evt);
            }
        });
        primeiroAcessoPanel.add(logarPrimAcesButton);
        logarPrimAcesButton.setBounds(380, 80, 80, 40);

        cancelarPrimAcesButton.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        cancelarPrimAcesButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/delfos/res/cancelar45x45.png"))); // NOI18N
        cancelarPrimAcesButton.setToolTipText("Cancelar");
        primeiroAcessoPanel.add(cancelarPrimAcesButton);
        cancelarPrimAcesButton.setBounds(290, 80, 80, 40);
        primeiroAcessoPanel.add(logotipoLabel1);
        logotipoLabel1.setBounds(0, 20, 210, 170);

        fundoTelaPrimAcesLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/delfos/res/fundotelaLogin523x197.png"))); // NOI18N
        primeiroAcessoPanel.add(fundoTelaPrimAcesLabel);
        fundoTelaPrimAcesLabel.setBounds(-7, 0, 600, 190);

        jPanel1.add(primeiroAcessoPanel);
        primeiroAcessoPanel.setBounds(0, -1, 590, 190);
        primeiroAcessoPanel.setVisible(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 592, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 192, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void senhaFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_senhaFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_senhaFieldActionPerformed

    private void logarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logarButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_logarButtonActionPerformed

    private void logarPrimAcesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logarPrimAcesButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_logarPrimAcesButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelarButton;
    private javax.swing.JButton cancelarPrimAcesButton;
    private javax.swing.JTextField cpfField;
    private javax.swing.JLabel cpfLabel;
    private javax.swing.JLabel fundoTelaLabel;
    private javax.swing.JLabel fundoTelaPrimAcesLabel;
    private javax.swing.JLabel informativoLabel;
    private javax.swing.JLabel informativoLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton logarButton;
    private javax.swing.JButton logarPrimAcesButton;
    private javax.swing.JTextField loginField;
    private javax.swing.JLabel loginLabel;
    private javax.swing.JPanel loginPanel;
    private javax.swing.JLabel logotipoLabel1;
    private javax.swing.JButton primeiroAcesButton;
    private javax.swing.JPanel primeiroAcessoPanel;
    private javax.swing.JPasswordField senhaField;
    private javax.swing.JLabel senhaLabel;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the cancelarButton
     */
    public javax.swing.JButton getCancelarButton() {
        return cancelarButton;
    }

    /**
     * @return the cancelarPrimAcesButton
     */
    public javax.swing.JButton getCancelarPrimAcesButton() {
        return cancelarPrimAcesButton;
    }

    /**
     * @return the cpfField
     */
    public javax.swing.JTextField getCpfField() {
        return cpfField;
    }

    /**
     * @return the cpfLabel
     */
    public javax.swing.JLabel getCpfLabel() {
        return cpfLabel;
    }

    /**
     * @return the fundoTelaLabel
     */
    public javax.swing.JLabel getFundoTelaLabel() {
        return fundoTelaLabel;
    }

    /**
     * @return the fundoTelaPrimAcesLabel
     */
    public javax.swing.JLabel getFundoTelaPrimAcesLabel() {
        return fundoTelaPrimAcesLabel;
    }

    /**
     * @return the informativoLabel
     */
    public javax.swing.JLabel getInformativoLabel() {
        return informativoLabel;
    }

    /**
     * @return the informativoLabel1
     */
    public javax.swing.JLabel getInformativoLabel1() {
        return informativoLabel1;
    }

    /**
     * @return the logarButton
     */
    public javax.swing.JButton getLogarButton() {
        return logarButton;
    }

    /**
     * @return the logarPrimAcesButton
     */
    public javax.swing.JButton getLogarPrimAcesButton() {
        return logarPrimAcesButton;
    }

    /**
     * @return the loginField
     */
    public javax.swing.JTextField getLoginField() {
        return loginField;
    }

    /**
     * @return the loginLabel
     */
    public javax.swing.JLabel getLoginLabel() {
        return loginLabel;
    }

    /**
     * @return the loginPanel
     */
    public javax.swing.JPanel getLoginPanel() {
        return loginPanel;
    }

    /**
     * @return the logotipoLabel
     */
   
    /**
     * @return the logotipoLabel1
     */
    public javax.swing.JLabel getLogotipoLabel1() {
        return logotipoLabel1;
    }

    /**
     * @return the primeiroAcesButton
     */
    public javax.swing.JButton getPrimeiroAcesButton() {
        return primeiroAcesButton;
    }

    /**
     * @return the primeiroAcessoPanel
     */
    public javax.swing.JPanel getPrimeiroAcessoPanel() {
        return primeiroAcessoPanel;
    }

    /**
     * @return the senhaField
     */
    public javax.swing.JPasswordField getSenhaField() {
        return senhaField;
    }

    /**
     * @return the senhaLabel
     */
    public javax.swing.JLabel getSenhaLabel() {
        return senhaLabel;
    }

    
}
