/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.swing.view;

import javax.swing.JDesktopPane;
import javax.swing.JMenuItem;

/**
 *
 * @author rafaelgentil
 */
public class TelaPrincipalView extends javax.swing.JFrame {

    /**
     * Creates new form TelaPrincipalView
     */
    public TelaPrincipalView() {
        
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jDesktopPane = new javax.swing.JDesktopPane();
        fundoTelaLabel = new javax.swing.JLabel();
        barraMenuBar = new javax.swing.JMenuBar();
        cadastro_menu = new javax.swing.JMenu();
        menu_ItemPaciente = new javax.swing.JMenuItem();
        menu_IItemProfissional = new javax.swing.JMenuItem();
        menu_ItemAtendente = new javax.swing.JMenuItem();
        menu_ItemAdm = new javax.swing.JMenuItem();
        prontuario_Menu = new javax.swing.JMenu();
        CriariProntuarioMenuItem = new javax.swing.JMenuItem();
        opcoes_Menu = new javax.swing.JMenu();
        DeslogarMenuItem = new javax.swing.JMenuItem();
        sairMenuItem = new javax.swing.JMenuItem();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setText("Tela Principal\n     *      Aluno\n     *      Professor\n     *      Grade de Horario\n     *      Historico\n     *      Busca Generica\n     *      Turma (Incompleta)\n     *      Curso\n     *      Semestre\n     *      Disciplina\n     *      Departamento");
        jScrollPane1.setViewportView(jTextArea1);
        jTextArea1.setVisible(false);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(null);
        getContentPane().add(jDesktopPane);
        jDesktopPane.setBounds(0, 0, 950, 540);

        fundoTelaLabel.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        getContentPane().add(fundoTelaLabel);
        fundoTelaLabel.setBounds(0, 0, 0, 0);

        barraMenuBar.setBorder(new javax.swing.border.MatteBorder(null));

        cadastro_menu.setText("Cadastro");

        menu_ItemPaciente.setText("Paciente");
        cadastro_menu.add(menu_ItemPaciente);

        menu_IItemProfissional.setText("Profissional De Saúde");
        menu_IItemProfissional.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_IItemProfissionalActionPerformed(evt);
            }
        });
        cadastro_menu.add(menu_IItemProfissional);

        menu_ItemAtendente.setText("Atendente");
        cadastro_menu.add(menu_ItemAtendente);

        menu_ItemAdm.setText("Administrador");
        cadastro_menu.add(menu_ItemAdm);

        barraMenuBar.add(cadastro_menu);

        prontuario_Menu.setText("Prontuário");
        prontuario_Menu.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N

        CriariProntuarioMenuItem.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        CriariProntuarioMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/delfos/res/deslogar0x30.png"))); // NOI18N
        CriariProntuarioMenuItem.setText("Criar Prontuário");
        prontuario_Menu.add(CriariProntuarioMenuItem);

        barraMenuBar.add(prontuario_Menu);

        opcoes_Menu.setText("Opções");

        DeslogarMenuItem.setText("Deslogar");
        DeslogarMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeslogarMenuItemActionPerformed(evt);
            }
        });
        opcoes_Menu.add(DeslogarMenuItem);

        sairMenuItem.setText("Sair");
        sairMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sairMenuItemActionPerformed(evt);
            }
        });
        opcoes_Menu.add(sairMenuItem);

        barraMenuBar.add(opcoes_Menu);

        setJMenuBar(barraMenuBar);

        setSize(new java.awt.Dimension(961, 562));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void DeslogarMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeslogarMenuItemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DeslogarMenuItemActionPerformed

    private void sairMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sairMenuItemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sairMenuItemActionPerformed

    private void menu_IItemProfissionalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_IItemProfissionalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menu_IItemProfissionalActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipalView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipalView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipalView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipalView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipalView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem CriariProntuarioMenuItem;
    private javax.swing.JMenuItem DeslogarMenuItem;
    private javax.swing.JMenuBar barraMenuBar;
    private javax.swing.JMenu cadastro_menu;
    private javax.swing.JLabel fundoTelaLabel;
    private javax.swing.JDesktopPane jDesktopPane;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JMenuItem menu_IItemProfissional;
    private javax.swing.JMenuItem menu_ItemAdm;
    private javax.swing.JMenuItem menu_ItemAtendente;
    private javax.swing.JMenuItem menu_ItemPaciente;
    private javax.swing.JMenu opcoes_Menu;
    private javax.swing.JMenu prontuario_Menu;
    private javax.swing.JMenuItem sairMenuItem;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the fundoTelaLabel
     */
    public javax.swing.JLabel getFundoTelaLabel() {
        return fundoTelaLabel;
    }

    /**
     * @return the Cadas_Paciente__It_menu
     */
   
    /**
     * @param Cadas_Paciente__It_menu the Cadas_Paciente__It_menu to set
     */
    
    /**
     * @return the CriariProntuarioMenuItem
     */
    public javax.swing.JMenuItem getCriariProntuarioMenuItem() {
        return CriariProntuarioMenuItem;
    }

    /**
     * @param CriariProntuarioMenuItem the CriariProntuarioMenuItem to set
     */
    public void setCriariProntuarioMenuItem(javax.swing.JMenuItem CriariProntuarioMenuItem) {
        this.CriariProntuarioMenuItem = CriariProntuarioMenuItem;
    }

    /**
     * @return the DelogarMenuItem
     */
    public javax.swing.JMenuItem getDelogarMenuItem() {
        return DeslogarMenuItem;
    }

    /**
     * @param DelogarMenuItem the DelogarMenuItem to set
     */
    public void setDelogarMenuItem(javax.swing.JMenuItem DelogarMenuItem) {
        this.DeslogarMenuItem = DelogarMenuItem;
    }

    /**
     * @return the barraMenuBar
     */
    public javax.swing.JMenuBar getBarraMenuBar() {
        return barraMenuBar;
    }

    /**
     * @param barraMenuBar the barraMenuBar to set
     */
    public void setBarraMenuBar(javax.swing.JMenuBar barraMenuBar) {
        this.barraMenuBar = barraMenuBar;
    }

    /**
     * @return the cadastrar_Adm_ItMenu
     */
   
    /**
     * @return the cadastrar_Profissional_ItMenu
     */
  
    /**
     * @return the opcoes_Menu
     */
    public javax.swing.JMenu getOpcoes_Menu() {
        return opcoes_Menu;
    }

    /**
     * @param opcoes_Menu the opcoes_Menu to set
     */
    public void setOpcoes_Menu(javax.swing.JMenu opcoes_Menu) {
        this.opcoes_Menu = opcoes_Menu;
    }

    /**
     * @return the prontuario_Menu
     */
    public javax.swing.JMenu getProntuario_Menu() {
        return prontuario_Menu;
    }

    /**
     * @param prontuario_Menu the prontuario_Menu to set
     */
    public void setProntuario_Menu(javax.swing.JMenu prontuario_Menu) {
        this.prontuario_Menu = prontuario_Menu;
    }

    /**
     * @return the sairMenuItem
     */
    public javax.swing.JMenuItem getSairMenuItem() {
        return sairMenuItem;
    }

    /**
     * @param sairMenuItem the sairMenuItem to set
     */
    public void setSairMenuItem(javax.swing.JMenuItem sairMenuItem) {
        this.sairMenuItem = sairMenuItem;
    }

    /**
     * @return the cadastro_menu
     */
    public javax.swing.JMenu getCadastro_menu() {
        return cadastro_menu;
    }

    /**
     * @param cadastro_menu the cadastro_menu to set
     */
    public void setCadastro_menu(javax.swing.JMenu cadastro_menu) {
        this.cadastro_menu = cadastro_menu;
    }

    /**
     * @return the menu_IItemProfissional
     */
    public javax.swing.JMenuItem getMenu_IItemProfissional() {
        return menu_IItemProfissional;
    }

    /**
     * @param menu_IItemProfissional the menu_IItemProfissional to set
     */
    public void setMenu_IItemProfissional(javax.swing.JMenuItem menu_IItemProfissional) {
        this.menu_IItemProfissional = menu_IItemProfissional;
    }

    /**
     * @return the menu_ItemAdm
     */
    public javax.swing.JMenuItem getMenu_ItemAdm() {
        return menu_ItemAdm;
    }

    /**
     * @param menu_ItemAdm the menu_ItemAdm to set
     */
    public void setMenu_ItemAdm(javax.swing.JMenuItem menu_ItemAdm) {
        this.menu_ItemAdm = menu_ItemAdm;
    }

    /**
     * @return the menu_ItemAtendente
     */
    public javax.swing.JMenuItem getMenu_ItemAtendente() {
        return menu_ItemAtendente;
    }

    /**
     * @param menu_ItemAtendente the menu_ItemAtendente to set
     */
    public void setMenu_ItemAtendente(javax.swing.JMenuItem menu_ItemAtendente) {
        this.menu_ItemAtendente = menu_ItemAtendente;
    }

    /**
     * @return the menu_ItemPaciente
     */
    public javax.swing.JMenuItem getMenu_ItemPaciente() {
        return menu_ItemPaciente;
    }

    /**
     * @param menu_ItemPaciente the menu_ItemPaciente to set
     */
    public void setMenu_ItemPaciente(javax.swing.JMenuItem menu_ItemPaciente) {
        this.menu_ItemPaciente = menu_ItemPaciente;
    }


    

    
    

    
}
